name: CI

on:
  pull_request:
  push:
    branches:
      - main
      # - master
      # - develop

env:
  CARGO_TERM_COLOR: always

# ensure that the workflow is only triggered once per PR, subsequent pushes to the PR will cancel
# and restart the workflow. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Nix package manager
      uses: DeterminateSystems/nix-installer-action@main
    #
    # - name: Setup Nix cache
    #   uses: DeterminateSystems/magic-nix-cache-action@main

    - name: Build
      # run: nix develop --command cargo build --verbose
      run: nix build
